### ISSUE TITLE
Exception when deploying war file

### ISSUE THREAD

**Issue by kastork** [tutumcloud/buildstep#6]
I have a grails 2.4.4 app that builds into a war.  This project runs fine locally, and I've successfully used the tutum/tomcat container to get it running as well.  When trying the tutum/buildstep container, the instructions for building the container seem to work, although I get some warnings (all indications are that the grails version is properly detected).

```
-----> Executing ./grailsw -plain-output -Divy.default.ivy.user.dir=/cache war --non-interactive
Mar 2, 2015 4:42:40 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
```

If that warning is a problem, I don't think it is impacting me (yet) because I can't get the container to run.

```
|Done creating WAR target/heroku-noodle-0.1.war
-----> No server directory found. Adding jetty-runner 8.1.10.v20130312 automatically.
```

But when running I get an exception

```
2015-03-02 16:44:56.201:INFO:omjr.Runner:Runner
java.lang.NumberFormatException: For input string: "target/heroku-noodle-0.1.war"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:481)
	at java.lang.Integer.parseInt(Integer.java:514)
	at org.mortbay.jetty.runner.Runner.configure(Runner.java:195)
	at org.mortbay.jetty.runner.Runner.main(Runner.java:632)
Usage: java [-DDEBUG] [-Djetty.home=dir] -jar jetty-runner.jar [--help|--version] [ server opts] [[ context opts] context ...]
```

I've set `grails.application.container=jetty` in my system.properties file.

My Procfile looks like so..

```
web: java $JAVA_OPTS -jar server/jetty-runner.jar --port $PORT target/*.war
```

**Comment by kastork** [comment]
Looks like $PORT isn't resolving to the value passed in with -p.  for example:

`docker run -p 8080:8080 kastork/heroku-noodle`  or
`docker run -p 8080 kastork/heroku-noodle`

Discovered this by changing to the webapp-runner instead of jetty.  It reported

`Exception in thread "main" com.beust.jcommander.ParameterException: "--port": couldn't convert "target/heroku-noodle-0.1.war" to an integer`

**Comment by fermayo** [comment]
I think you can just define the environment variable `-e PORT=8080` when launching the build step and it should work just fine. Can you confirm?

**Comment by kastork** [comment]
yes thanks
