### ISSUE TITLE
question: on-the-fly usage with GIT_REPO not working, can you spot anything?

### ISSUE THREAD

**Issue by tony-kerz** [tutumcloud/buildstep#8]
hi,

locally on my macbook (with kite-matic/docker-machine), trying the following command:
```
docker run -d -e GIT_REPO=https://github.com/tony-kerz/hubot-scratch.git -e HUBOT_CAMPFIRE_ACCOUNT=kerzsoft -e HUBOT_CAMPFIRE_TOKEN=<token> -e HUBOT_CAMPFIRE_ROOMS=614950 tutum/buildstep bin/hubot -a campfire -n bot
```
yields:
```
No logs for this container
```
and...
```
docker run -d -e GIT_REPO=https://github.com/tony-kerz/hubot-scratch.git -e HUBOT_CAMPFIRE_ACCOUNT=kerzsoft -e HUBOT_CAMPFIRE_TOKEN=<token> -e HUBOT_CAMPFIRE_ROOMS=614950 tutum/buildstep /start exec
```
yields:
```
cat: /app/Procfile: No such file or directory
```
but the following works:
```
docker build -t myuser/myapp .
docker run -d -e HUBOT_CAMPFIRE_ACCOUNT=kerzsoft -e HUBOT_CAMPFIRE_TOKEN=<token> -e HUBOT_CAMPFIRE_ROOMS=614950 myuser/myapp
```
can you spot anything wrong around the 'on-the-fly' usage or provide any troubleshooting guidance?

full disclosure: docker noob (also, please let me know if there is a better forum for these type of questions than the repo issues)

regards,
tony.

**Comment by fermayo** [comment]
Fixed in f6a0d89a539882ed8779209a8b3817386d839bc7

Running `docker run -d -e GIT_REPO=https://github.com/tony-kerz/hubot-scratch.git -e HUBOT_CAMPFIRE_ACCOUNT=kerzsoft -e HUBOT_CAMPFIRE_TOKEN=<token> -e HUBOT_CAMPFIRE_ROOMS=614950 tutum/buildstep exec` should now work
